// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"telegra/ent/account"
	"telegra/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetShortName sets the "short_name" field.
func (au *AccountUpdate) SetShortName(s string) *AccountUpdate {
	au.mutation.SetShortName(s)
	return au
}

// SetAuthorName sets the "author_name" field.
func (au *AccountUpdate) SetAuthorName(s string) *AccountUpdate {
	au.mutation.SetAuthorName(s)
	return au
}

// SetAuthorURL sets the "author_url" field.
func (au *AccountUpdate) SetAuthorURL(s string) *AccountUpdate {
	au.mutation.SetAuthorURL(s)
	return au
}

// SetAccessToken sets the "access_token" field.
func (au *AccountUpdate) SetAccessToken(s string) *AccountUpdate {
	au.mutation.SetAccessToken(s)
	return au
}

// SetAuthURL sets the "auth_url" field.
func (au *AccountUpdate) SetAuthURL(s string) *AccountUpdate {
	au.mutation.SetAuthURL(s)
	return au
}

// SetPageCount sets the "page_count" field.
func (au *AccountUpdate) SetPageCount(i int) *AccountUpdate {
	au.mutation.ResetPageCount()
	au.mutation.SetPageCount(i)
	return au
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (au *AccountUpdate) SetNillablePageCount(i *int) *AccountUpdate {
	if i != nil {
		au.SetPageCount(*i)
	}
	return au
}

// AddPageCount adds i to the "page_count" field.
func (au *AccountUpdate) AddPageCount(i int) *AccountUpdate {
	au.mutation.AddPageCount(i)
	return au
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			if au.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   account.Table,
			Columns: account.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: account.FieldID,
			},
		},
	}
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.ShortName(); ok {
		_spec.SetField(account.FieldShortName, field.TypeString, value)
	}
	if value, ok := au.mutation.AuthorName(); ok {
		_spec.SetField(account.FieldAuthorName, field.TypeString, value)
	}
	if value, ok := au.mutation.AuthorURL(); ok {
		_spec.SetField(account.FieldAuthorURL, field.TypeString, value)
	}
	if value, ok := au.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := au.mutation.AuthURL(); ok {
		_spec.SetField(account.FieldAuthURL, field.TypeString, value)
	}
	if value, ok := au.mutation.PageCount(); ok {
		_spec.SetField(account.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedPageCount(); ok {
		_spec.AddField(account.FieldPageCount, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetShortName sets the "short_name" field.
func (auo *AccountUpdateOne) SetShortName(s string) *AccountUpdateOne {
	auo.mutation.SetShortName(s)
	return auo
}

// SetAuthorName sets the "author_name" field.
func (auo *AccountUpdateOne) SetAuthorName(s string) *AccountUpdateOne {
	auo.mutation.SetAuthorName(s)
	return auo
}

// SetAuthorURL sets the "author_url" field.
func (auo *AccountUpdateOne) SetAuthorURL(s string) *AccountUpdateOne {
	auo.mutation.SetAuthorURL(s)
	return auo
}

// SetAccessToken sets the "access_token" field.
func (auo *AccountUpdateOne) SetAccessToken(s string) *AccountUpdateOne {
	auo.mutation.SetAccessToken(s)
	return auo
}

// SetAuthURL sets the "auth_url" field.
func (auo *AccountUpdateOne) SetAuthURL(s string) *AccountUpdateOne {
	auo.mutation.SetAuthURL(s)
	return auo
}

// SetPageCount sets the "page_count" field.
func (auo *AccountUpdateOne) SetPageCount(i int) *AccountUpdateOne {
	auo.mutation.ResetPageCount()
	auo.mutation.SetPageCount(i)
	return auo
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillablePageCount(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetPageCount(*i)
	}
	return auo
}

// AddPageCount adds i to the "page_count" field.
func (auo *AccountUpdateOne) AddPageCount(i int) *AccountUpdateOne {
	auo.mutation.AddPageCount(i)
	return auo
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	var (
		err  error
		node *Account
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			if auo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = auo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, auo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Account)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AccountMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   account.Table,
			Columns: account.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: account.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.ShortName(); ok {
		_spec.SetField(account.FieldShortName, field.TypeString, value)
	}
	if value, ok := auo.mutation.AuthorName(); ok {
		_spec.SetField(account.FieldAuthorName, field.TypeString, value)
	}
	if value, ok := auo.mutation.AuthorURL(); ok {
		_spec.SetField(account.FieldAuthorURL, field.TypeString, value)
	}
	if value, ok := auo.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
	}
	if value, ok := auo.mutation.AuthURL(); ok {
		_spec.SetField(account.FieldAuthURL, field.TypeString, value)
	}
	if value, ok := auo.mutation.PageCount(); ok {
		_spec.SetField(account.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedPageCount(); ok {
		_spec.AddField(account.FieldPageCount, field.TypeInt, value)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
