// Code generated by ent, DO NOT EDIT.

package ent

import (
	"telegra/ent/account"
	"telegra/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescPageCount is the schema descriptor for page_count field.
	accountDescPageCount := accountFields[5].Descriptor()
	// account.DefaultPageCount holds the default value on creation for the page_count field.
	account.DefaultPageCount = accountDescPageCount.Default.(int)
}
